version: '3'
services:
  dev:
    container_name: dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    volumes:
      - ./:/app
    ports:
      - "30001:30001"
      - "30002:30002"
    env_file: 
      - ./.env